<link rel="stylesheet" href="../public/css/update.css">
<form action="" method="POST">
    <div class="title">
        <label>Chapitre : </label>
        <input type="text" name="chapter" value="<?php echo($chapter);?>">
        <label>Titre : </label>
        <input type="text" name="title" value="<?php echo($title);?>">
    </div>
    <div class="contenu">
        <label for="contenu"></label>
        <textarea name="contenu" id="textarea"><?php echo($contenu);?></textarea>
        <input type="hidden" name="envoyeur" value="<?php echo($_GET['id']);?>"><br>
        <input type="submit" value="Modifier">
    </div>
</form>
    