<h1>Billet simple pour l'Alaska</h1><?php
$array = $readComments->fetchAll();
while($donnees = $readArticle->fetch()){ ?>
<div class="accordion" id="accordionExample">
    <div class="card">
        <div class="card-header" id="headingOne">
            <h2 class="mb-0">
            <button class="btn btn-link" type="button" data-toggle="collapse"
                data-target="#collapse<?php echo($donnees['id']);?>" aria-expanded="false"
                aria-controls="collapse<?php echo($donnees['id']);?>">
                Chapitre <?php echo($donnees['chapter']."&nbsp".$donnees['title']);?> créer le
                <?php echo($donnees['date']);?>
            </button>
            </h2>
        </div>
        <div id="collapse<?php echo($donnees['id']);?>" class="collapse" aria-labelledby="headingOne"
            data-parent="#accordionExample">
            <div class="card card-body">
                <div>
                    <!--card-body--> contenu du chapitre <?php echo($donnees['chapter']);?>
                </div>
                <div>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#writeComment<?php echo($donnees['id']);?>">
                        Commentaire
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="writeComment<?php echo($donnees['id']);?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalCenterTitle">Laissez un commentaire</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <form action="" method="post">
                                        <label for="pseudo">pseudo : </label>
                                        <input type="text" name="pseudo" id="pseudo"><br>
                                        <label for="email">Email : </label>
                                        <input type="email" name="email"><br>
                                        <label for="commentaire">Commentaire : </label>
                                        <textarea name="commentaire" ></textarea>
                                        <input type="hidden" name="article_id_createComment" value="<?php echo($donnees['id']);?>">
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                                    <button type="button" class="btn btn-primary" id="modal_envoyer" onclick="this.form.submit()">Envoyer</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!---->
                </div>
                <div>
                    <!--read comments-->
                    <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#readCommentModal<?php echo($donnees['id']);?>">
                        Lire les commentaires
                        </button>
                    
                    <!-- Modal -->
                    <div class="modal fade" id="readCommentModal<?php echo($donnees['id']);?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Commentaires</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <?php
                            if(!empty($array)){
                                $verification_commentaire = "";
                                foreach ($array as $f) {
                                    if($donnees['id']== $f['article_id']){
                                        $verification_commentaire = true;
                                        ?> <p>Commentaire de <?php echo($f['pseudo']);?> laissé le <?php echo($f['date']);?><br>
                                        <?php echo($f['commentaire']);?></p><br><br>
                                        <!---Signaler commentaire-->
                                        <!-- Button trigger modal -->
                                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#signaler<?php echo($f['id']);?>">
                                            Signaler ce commentaire
                                        </button>

                                        <!-- Modal -->
                                        <div class="modal fade" id="signaler<?php echo($f['id']);?>" tabindex="-1" role="dialog" aria-labelledby="signaler" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="signaler">Signalement</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <form action="" method="post">
                                                            <select name="motif">
                                                                <option value="">Motif du signalement</option>
                                                                <option value="harcelement">harcelement</option>
                                                                <option value="propos injurieux">propos injurieux</option>
                                                                <option value="menace">menace</option>
                                                            </select>
                                                            <input type="hidden" name="signaler">
                                                            <input type="hidden" name="commentaire_id" value="<?php echo($f['id']);?>">
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                                                        <button type="button" class="btn btn-primary" onclick="this.form.submit()">Signaler</button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>  
                                        <?php                                        
                                    }
                                };
                            }
                            if($verification_commentaire != true){
                                echo "Il n'y a pas de commentaire";
                            }?>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                        </div>
                    </div>
                </div>
            </div>

                </div>
            </div>
        </div>
    </div>
</div>
<?php }?>